export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SAVE_USER_DETAILS = "SAVE_USER_DETAILS";
export const GET_USER_DETAILS = "GET_USER_DETAILS";